### ISSUE TITLE
[Summary on staging bug fix] [Fix inside]

### ISSUE THREAD

**Issue by ntvm** [SillyTavern/SillyTavern#1020]
Summary was broken since prompt manager update merged on staging, there already fixed variant:

public/scripts/openai.js 684

    // Tavern Extra (changed)
    const summary = extensionPrompts['1_memory'];
    if (summary && summary.value) systemPrompts.push({
        role: 'system',
        content: summary.value,
        identifier: 'summary'
    });

Instead 

    // Tavern Extras
    const summary = extensionPrompts['1_memory'];
    if (summary && summary.content) systemPrompts.push({
        role: 'system',
        content: summary.content,
        identifier: 'summary'
    });

Plus if I catched original idea, summary supposed to be inside scenario or after scenario instead of part of main, so, probably it should be like that:
public/scripts/openai.js 618

    // Tavern Extras - Summary (changed)
    if (prompts.has('summary')) chatCompletion.insert(Message.fromPrompt(prompts.get('summary')), 'scenario');

Instead of

    // Tavern Extras - Summary
    if (prompts.has('summary')) chatCompletion.insert(Message.fromPrompt(prompts.get('summary')), 'main');

**Comment by Cohee1207** [comment]
Thanks, I'll double-check it and apply the fix. Alas, I only tested summaries on prompt manager with an in-chat injection strategy, so may have missed this configuration.

Regarding the second point, "After scenario" is an outdated term that should be replaced with "After Main Prompt / Story String" across the board since you can now rearrange prompt blocks for all APIs, but historically Scenario was previously the last part of the character card, hence the name.

**Comment by Cohee1207** [comment]
I fixed it with your code and it worked well. Feel free to double-check on your end if needed.
Cheers.
