### ISSUE TITLE
[FEATURE_REQUEST] Add Superboogav2 for "long-term-memory"

### ISSUE THREAD

**Issue by minipasila** [SillyTavern/SillyTavern#1212]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Oobabooga recently made a new version of their vector based memory system that does a lot more than the previous version. [Link to the extension.](https://github.com/oobabooga/text-generation-webui/tree/main/extensions/superboogav2) It seems to pre-process the messages before adding them to a database. It would be cool if this could somehow be implemented in SillyTavern.

### Describe the solution you'd like

There might be an API that can be used from the extension but I'm not sure how useful it is. It likely would have to be implemented to the SillyTavern Extras module.

### Describe alternatives you've considered

I could keep using the very basic ChromaDB extension or just use Ooba with the new extension.

### Additional context

The extension: https://github.com/oobabooga/text-generation-webui/tree/main/extensions/superboogav2

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

No

**Comment by Cohee1207** [comment]
It's good that you quoted the long-term memory because I'm very skeptical about using vector storage for this. I haven't seen any documented research proving that it actually improves the user experience in chat RP with anything but direct Q&A, i.e. expert systems.
Let's first break down how it works: previous messages or other data is transformed to assign some numeric values to them. Then when the prompt is built, recent inputs are also converted to numbers and compared to bring up the most matching past records. That's not how memory works, it's not a collection of the most important facts, but rather a more "effective" way to pack your context by putting more relevant records in it that would've fallen out of context otherwise.
Now, a more relevant example: let's imagine that you stated in your first message that you were born in Italy. Soon or later this fact will be "forgotten" because the message containing this fact will be pushed out of context. And the most important catch in all of this: unless you directly ask what's your nationality, the vector store will never be able to randomly bring up this fact for consideration, or randomly mention something related to Italy, because nothing in the recent chat history can trigger this "memory".
Sorry for the long rant, but after several experiments with different vector storages and other means of memory simulation, I can confidently say that it's not a solution that we should be focused on. This is a won't fix.

**Comment by fielding** [comment]
I just wanted to chime in and second what you said @Cohee1207. If anything, it can actually confuse the persona/character due to older chat excerpts having outdated answers or information that ultimately influence the tokens it generates for it's current response. 

I wish I could comment on what I think the ideal long-term memory system would look like, but I don't see one existing that doesn't involve some sort of reflection/updating. Also, matching on the user's message via similarity search is flawed as you pointed out. On top of the evolving store that I mentioned above, if there is a solution that involves searching, it has to be presented as a tool that the LLM decides what the query or what useful queries to find potentially complimentary information has to be.


Anyway, sorry for necroing this... but do you have any new thoughts on a possible solution since you commented last Oct?

**Comment by minipasila** [comment]
This https://github.com/brucepro/Memoir supposedly helps alleviate some of the problems Cohee mentioned but whether or not it actually works well is yet to be seen (haven't tested it yet).
