### ISSUE TITLE
[FEATURE_REQUEST] Regex functionality

### ISSUE THREAD

**Issue by a1anon** [SillyTavern/SillyTavern#1270]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

Status blocks at the end of the model’s message (time, date, location, weather, character’s mood, etc.) greatly help the model keep track of time, environment, etc., but they greatly clutter the context over time.

### Describe the solution you'd like

Add a custom timer feature to the Regex script editor, which would count messages and run the Regex script not on the last response, but for example on the previous one if the timer is set to 1. For example, there are 3 messages from the model:
1) test1
2) test2
3) test3
If the regex script timer is set to 0, then message 3 (test3) is processed, if timer = 1, then the regex will process message 2, if timer is 2, then message 1 will be processed.
The larger the number in the regex script timer, the later the message in the chat history it affects.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by dariox1337** [comment]
I have a similar request. I'm telling my bots to write their internal thoughts inside html comments, and then delete these thoughts with regex, but I'd love if it was possible to keep thoughts for a couple of messages, so that the bot remembered its plans. The issue is that while the bot might be planning to manipulate user and acts a certain way (like crying), in a few messages, the acting become real because the bot forgets its internal thoughts.

Anyway, closer to the point. I think it'd be nice to have an option to limit the scope of regex substitutions to a number a messages. **A simple setting, which would be enough: "this regex substitution works only STARTING FROM chat depth X" or "this regex substitution works only UP TO chat depth X."** Ideally, we'd be able to specify to whose messages it applies (for group chats). Even more advanced: having an option to set the step between applications, meaning the regex will apply to every 2nd, 3rd, Nth message.

**Comment by nothingsuspiciousright** [comment]
On ne slishit, u nego airpodsi...
