### ISSUE TITLE
[BUG_OR_FEATURE_REQUEST] Height/length measurements using freedom units.

### ISSUE THREAD

**Issue by Crozzwise** [SillyTavern/SillyTavern#1291]
### Have you searched for similar requests?

Yes

### Describe the solution you'd like

I've recently encountered a model that was quite fond of giving the height of every new story character in freedom units.

e.g.: She stands at 5'7"

The double-quotes mess up normal quoting obviously. Catching all use cases for when a length in inches might be given in this way seems a bit too much effort, but throwing in an easy regex for catching the most common use of height given in this format and then treating the double quotes as plain text might be worth it.

### Priority

Low (Nice-to-have)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
You can turn off Markdown auto-fix so it won't try to match unbalanced quotes. Alternatively, ask the model to use metric units (somewhere in the system prompt).
Unrelated, but one more thing that gets most of the models confused is the 12H time format.

**Comment by Crozzwise** [comment]
If you're referring to "Auto-fix Markdown", I always have that off. And the model was actually introducing multiple persons and gave a height for each, so there were matching double-quotes. But I appreciate your sentiment of telling users from the usofa to start using metric or go envelopamember.

**Comment by keturn** [comment]
We might be able to cook up a reasonable heuristic for this? Say that a close-quote is always preceded by a non-digit, i.e. `[\D]"`

Hmm. That's probably true for prose, because dialog in quotes should generally terminate in some other punctuation, but if the model is, say, a coding assistant, that might be returning you snippets of some other syntax, that gets a bit riskier.

How about this: a regex substitution rule for this narrower (but common) case where a measurement is provided with feet _and_ inches:

```regex
(\d{1,2})'(\d{1,2})"
```
which replaces the straight quotes with the more typographically-appropriate [prime and double prime](https://en.wikipedia.org/wiki/Prime_(symbol)#Double_prime):

```
$1′$2″
```
That way, the double-prime won't get mistaken for a quotation mark by the quote-text parser.

Here's a more [elaborate version](https://regexr.com/7s2qc) that allows a bit of whitespace as well as some fractions:

```regex
\b(\d{1,2})'(\s?)(\d{0,2}?\s?[\d\/\.¼½¾⅐-⅞]{0,5})"
```
Replace With
```
$1′$2$3″
```
