### ISSUE TITLE
Want to add a proxy function

### ISSUE THREAD

**Issue by qw1642190428** [SillyTavern/SillyTavern#1359]
### Have you searched for similar requests?

None

### Is your feature request related to a problem? If so, please describe.

I am a user from China. Since Google Translate cannot be used in China, I need a VPN. Bing’s translation is too short and insufficient, so I hope to add a network output function to the front end, similar to the proxy function of Telegram. For example, the software I am using now It is v2rayN that acts as a proxy. I can use socks or http plus a port for local proxying. As for why not enable global proxying? Opening Global on a Chinese computer is equivalent to using an Argentinian VPN to browse American websites in the United States.

### Describe the solution you'd like

Add input interfaces for socks and http proxies on the front end so that all network requests of SillyTavern use these proxies to send and receive network requests.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by adastra9257** [comment]
@qw1642190428 If you are running on Linux, you can try running start script with proxychains or [gg](https://github.com/mzz2017/gg).

I believe there should also be an option to translate using LLM instead of the APIs. From my experience, LLM outperforms Google and DeepL in translation, especially when it comes to understanding complex expressions. I hope the developers can implement this.

**Comment by Erick0412-dev** [comment]
I have also encountered similar network issues, so I believe this feature is very important! Hope to add to the next version!
