### ISSUE TITLE
[Documents/simple mode] Inability to edit text other than last generation.

### ISSUE THREAD

**Issue by perkel666** [SillyTavern/SillyTavern#1496]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11

### Version

latest

### Describe the problem

When selecting /simple (document) chat style there is no way to edit generations other than last one. Icons are missing on right side.

Also proper support for Story mode would be nice. Aside from NovelAI (paid) and very buggy KoboldAI there isn't any front end that supports it.

I managed to "hack" it in silly tavern but that bug makes it almost impossible to use as in story mode you often want to correct and fix earlier parts.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Added ability to edit single document messages by clicking on them

**Comment by Danweel** [comment]
I just wanted to add a note here for people who might have been searching for why they suddenly _can't edit previous notes in SillyTavern_:

Setting your chat view to _Document_ as the **Chat Style** under **User Settings** isn't just an aesthetic difference, it affects your ability to edit anything other than the last prompt result (and summary, if you have Tracker on). If you revert your _Chat Syle_ back to one of the other two modes, (right now that's _Flat_ or _Bubbles_), it will restore the editing menu bar for all responses. 

The **Document** view actually affects not just the way it looks, but a **functionality** as well. It's easy to mistake since it's under '**UI Themes**' and I generally take that to be cosmetic-only changes. I'm not sure it rises to the level of 'bug', but I do find that a bit unclear and may have confused some people, (at least for a few minutes). 

It strikes me as not in the right place, or not annotated the way many other things are! I think I assumed anything I needed to know would be there on hover, since that's quite consistent for other items that have secondary or non-obvious effects. (Though that might not be doable in a dropdown. Maybe even just a note in brackets after the option name?)

**Comment by Cohee1207** [comment]
> The Document view actually affects not just the way it looks, but a functionality as well. It's easy to mistake since it's under 'UI Themes' and I generally take that to be cosmetic-only changes. I'm not sure it rises to the level of 'bug', but I do find that a bit unclear and may have confused some people, (at least for a few minutes).

FYI, Click-to-Edit mode has been decoupled from document mode in 1.13.0, and is now available for any chat style.
