### ISSUE TITLE
[BUG]/[Misunderstanding] Option "Execute on user message" in new QR not working.

### ISSUE THREAD

**Issue by valden80** [SillyTavern/SillyTavern#1643]
### Environment

Self-Hosted (Bare Metal)

### System

Firefox 115.2.0esr, Manjaro current.

### Version

SillyTavern1.11.2 staging

### Desktop Information

 - OS/Device: Manjaro Linux
 - Environment: local
 - Node.js: version 20.2.0
 - Browser: Firefox
 - Generation API: Oobaboga
 - Branch: staging
 - Model: any local

### Describe the problem

I assume, that option "Execute on user message" shall work this way: then I write message and press Enter this message will be replaced with the QR. 

So for test I want to make QR to add to all my messages prefix > - as for Text Adventure Game.

I made "> {{input}}" QR and set "Execute on user message" for it on in properties.

When I enter something and then press on this QR button in GUI with mouse - it's working as I want. Example: "I go forward" become and sent as "> I go forward".
When I enter text and press Enter - my message being sent directly as is: "I go forward", and in input field it replaced with "> {{input}}".

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
@LenAnderson one more requiring your input here

**Comment by LenAnderson** [comment]
*Execute on user message* runs after the message shows up in chat. This is intended and how the previous version of QR worked as well.
QRs currently don't have an auto execute that intercepts a user-sent message.

**Comment by Cohee1207** [comment]
Was it working before QR update? Previously auto-execute was running after message has been rendered as well.

**Comment by valden80** [comment]
Right now it's very confusing - different behavior of the same QR code/entry. I write something in input field then:
1. When activating by pressing QR GUI button by mouse: it's clearing user input field and process it as expected.
2. When activating (expect to - option named "Execute on user message") by pressing Enter - it's NOT process QR, but also REPLACE user input in the input field with the QR code.

By honest - I even can't get idea where second behavior may be used. It will replace text in input field after each time User pressing Enter and not process {{input}} macros.

**Comment by LenAnderson** [comment]
It does process the QR but the text is stuck in the input box on auto execute because the LLM is generating at that point and blocking user messages. It would send if you for example were on a group chat with all characters muted.
However, this functionality (and all auto executes, really) are probably more useful when used with slash commands / stscript, rather than plain messages.

**Comment by valden80** [comment]
Currently I don't see it useful, as it replace every user input - and it not selective at all. So user will need to manually clean input field before his next message entering. It's trigger on every pressing Enter - not possible to set it to trigger only for specific input.

**Comment by LenAnderson** [comment]
Like I said. Auto executes are mostly useful for scripts, not plain text. If you want it to only act on specific input you have `/if` at your disposal.

**Comment by valden80** [comment]
It's seems - I can't explain clearly, or you don't understand what I trying to say. My main concern here - behavior in **Input field**, where user entering text.

Setup of the QR:
1. Label = ">"
2. Message / Command = "> {{input}}"
3. Execute on user message = On

When I enter something as my message to AI and press Enter to send it, EVERY TIME my message replaced in **INPUT FIELD** to "> {{input}}" - exactly the script body from 2. 
So, to enter and send next message to AI I need to previously clean **input field** manually. For what this behavior is needed? It's not show processed script (macro {{input}} shown in the field as macro tag). It's not replace input on condition - it replace user input in **input field** ALWAYS.
For what it can be used? I don't understand it at all. It's only add inconvenience - need to remove unneeded text from input after every "Enter".

**Comment by LenAnderson** [comment]
The {{input}} macro not being resolved has been fixed earlier today. However, that does not change the rest of the behavior of non-command QRs with auto-execute on user input.
It will correctly put "> your input" into the input field now instead of "> {{input}}" but it will still not send anything because sending is blocked by the response being generated.

I can only repeat that there is not much point in having something other than a slash command set to auto-execute on user input. It will only trigger **after** your message has been sent, and in most cases that means that a response is currently being generated. This blocks the QR message from being sent and results in it just sitting in your input field...

**Comment by valden80** [comment]
Ok, I done update to last staging. Now it's still strange. I entering "I go forward":

1. When I press "Enter" - {{input}} replaced by nothing, sent original "I go forward" and in input field message replaced with ">". 
2. When i enter "I go forward" and press ">" label button of this QR with mouse - Message sent as "> I go forward" and input field is clean.

This is confusing, as the same QR script behave differently only by different activation method. With mouse activation it behave as expected, with keyboard - confusing...

Maybe renaming option "Execute on user message" to "Run after user's messages" will help to avoid such confusion. Right now it's doing something other, then most users will expect from option name. Or additional tool-tip with explanation will help greatly.

**Comment by LenAnderson** [comment]
The result is different because you are effectively doing two different things and the QR executes at a different time / app state.
When you press enter:
- your message is sent
- this clears the input field
- your message is written to chat
- this triggers the auto execute QR
- The QR executes and puts ">" plus the **current content** of the input field (which is blank) into the input field
- The QR tries to submit the input field, but can't because a generation is running

If you do the same manually you will see the same results:
- disable auto execute on the QR
- write your message
- send your message
- while the model is still generating, click the QR button

**Comment by valden80** [comment]
Yes, now it's clear for me how it's working, thanks for detailed explanation. 
But I still strongly suggest to change name of the option. "Execute on user message" - don't give right clue about the real processing logic for someone who do not know about it before. In most programming doc's "on user message" - usually means that message will be processed fully (event catcher and processor). In this case - it's doing most work after message but not with it's text. This was confused me, and for sure will confuse others.
