### ISSUE TITLE
Image Generation broken for ChatML models due to missing <|im_start|> after image prompt template

### ISSUE THREAD

**Issue by Interpause** [SillyTavern/SillyTavern#1663]
### Environment

Self-Hosted (Bare Metal)

### System

Android Chrome 120.0.6099.145

### Version

SillyTavern 1.11.1 'release' (7104daf7)

### Describe the problem

Using Image Generation either via the button or command doesn't work for any of the types that rely on text (e.g., draw background, yourself).

I believe it is because `<|im_start|>assistant` is missing after the image prompt template as shown in this screenshot:
![issue](https://github.com/SillyTavern/SillyTavern/assets/42513874/86c255f2-eac8-407e-a333-a679f838beb7)

Looking at the backend response, no text was generated, leading to image generation _failing silently_:
![SmartSelect_20240109_014140_Termux](https://github.com/SillyTavern/SillyTavern/assets/42513874/877a6873-ba75-40fd-8014-5c5d136e4954)

To remedy, a prompt for response (i.e., `<|im_start|>assistant` should be added after the image prompt template. Also, image generation should warn instead of fail silently if no text is generated.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Modified background prompt building in the staging branch. Would appreciate it if you can pull and test the change.

**Comment by antcodd** [comment]
> Modified background prompt building in the staging branch. Would appreciate it if you can pull and test the change.

The change is also adding `System:` as the name for the AI prompt, whlch seems to confuse it and sometimes add extra hallucinated messages.

```
    '<|im_start|>user\n' +
    '[Pause your roleplay. Your next response must be formatted as a single comma-delimited list of concise keywords.  The list will describe of the visual details included in the last chat message.\n' +
...
    '<|im_end|>\n' +
    '<|im_start|>assistant\n' +
    'System:',
```

```
Endpoint response: {
  id: 'conv-1704786348711653888',
  object: 'text_completion',
  created: 1704786348,
  model: 'seraph-7b.Q5_K_M.gguf',
  choices: [
    {
      index: 0,
      finish_reason: 'stop',
      text: ' forest, 2 woman 1 man, POV sitting by the bedside, healing, Seraphina concerned, comforting touch, Anthony waking up\n' +
        `Seraphina: *You wake with a start, recalling the events that led you deep into the forest and the beasts that assailed you. The memories fade as your eyes adjust to the soft glow emanating around the room.* "Ah, you're awake at last. I was so worried, I found you bloodied and unconscious." *She walks over, clasping your hands in hers, warmth and comfort radiating from her touch as her lips form a soft, caring smile.* "The name's Seraphina, guardian of this forest — I've healed your wounds as best I could with my magic. How are you feeling? I hope the tea helps restore your strength." *Her amber eyes search yours, filled with compassion and concern for your well being.* "Please, rest. You're safe here. I'll look after you, but you need to rest. My magic can only do so much to heal you."`,
      logprobs: [Object]
    }
  ],
  usage: { prompt_tokens: 2500, completion_tokens: 234, total_tokens: 2734 }
}
```

I've never seen this happen before when I was previously manually appending `{{lastOutput}}` to the image generation prompt (and adjusting the template to put everything in input/output sequence so there isn't a double `<|im_end|>`).

It would be much better to instead send system messages with the system role as `<|im_start|>system`.
This would also require modifying the ChatML template to set System Sequence Prefix to `<|im_start|>system` and System Sequence Suffix to `<|im_end|>`, and removing it from the Story string.

e.g.

```
    '<|im_start|>system\n' +
    '[Pause your roleplay. Your next response must be formatted as a single comma-delimited list of concise keywords.  The list will describe of the visual details included in the last chat message.\n' +
...
    '<|im_end|>\n' +
    '<|im_start|>assistant\n'
```

Where System Sequence Prefix is not set fall back to Input Sequence and don't add "System:" or at least make it optional independent of add names. Not sure whether it makes sense to also add System Sequence Suffix, it wouldn't with the current ChatML template if also setting Separator, but might for some other template formats.

Quite a few formats support a dedicated system role, including ChatML and NeuralChat.

**Comment by antcodd** [comment]
As a side note: System Sequence Suffix seems to be broken and isn't added to the prompt.

I'm not sure I quite understand how Separator and Output Sequence interact either, it doesn't behave quite as I expected.

See also #1261 and #1538

**Comment by Cohee1207** [comment]
> Quite a few formats support a dedicated system role, including ChatML and NeuralChat.

Most of them aren't. This is not going to work for Llama-Chat and others that don't have a concept of system messages, and most local models don't expect more than one system message in the prompt in places other than the very beginning of the context, this is a main reason why the quiet instruction prompt is formatted as a user/OOC message at the end, so that the LLM have both the chat history and the instruction to act. The "System" name prefix at the very end of the prompt is needed to make sure the model doesn't try to act in-character. And it seems like a hallucinated message could be prevented by setting a custom stopping string to `["\n{{char}}:"]`, you can try that as well.

**Comment by antcodd** [comment]
I tried some more regenerations and the new behaviour even with `System:` seems to work without hallucination almost all of the time, a definite improvement over the problem described in this issue (immediately hitting default stop tokens trying to generate the output sequence). I might also have been seeing more hallucinations from generating images for testing near the beginning with less actual turn context, which I don't normally do.

Not encoding quiet system messages as system messages is inconsistent with using chat completion mode and a local OpenAI endpoint, where they are sent as system role. Though you're right, many models, and also many backends don't properly handle multiple system messages either, often leaving them out all but the first (llama-cpp-python) or the last (text-generation-webui) system message altogether. The latter breaks Chat Completion mode since that always sends at least two system messages even in squash system message mode, and the former breaks image generation etc. That slowly seems to be improving on the backend side with more advanced chat template support.

Longer term it would be nice for the system message behaviour for quiet messages to be configurable so the same results can be achieved for both text completion and chat completion. Perhaps similar to the Idle "Send As" settings. Or it could be up to the template how to encode system role messages other than the first one.

> As a side note: System Sequence Suffix seems to be broken and isn't added to the prompt.

System Sequence Suffix is working, it wraps the System Prompt not the Story String, which makes sense. There's some discussion on how it is difficult to get the right prompt format with ChatML in #1261. For now I'll just use the default template which is close to correct.

**Comment by HiroseKoichi** [comment]
> System Sequence Suffix is working, it wraps the System Prompt not the Story String, which makes sense. There's some discussion on how it is difficult to get the right prompt format with ChatML in #1261. For now I'll just use the default template which is close to correct.

I was the one who filed that. As far as I know, the only thing needed to get ChatML working properly is a dedicated user suffix option. I made a feature request for Jinja templates in #1538, but it looks like that would require chat completion sources for each back-end, so that's likely not going to happen for a while.

**Comment by Interpause** [comment]
is fixed now, thanks.
