### ISSUE TITLE
NPM is not installed

### ISSUE THREAD

**Issue by Viking1811** [SillyTavern/SillyTavern#1732]
### Environment

Self-Hosted (Bare Metal)

### System

Linux Mint 21.2 Cinnamon

### Version

1.11.0

### Desktop Information

nodejs v12.22.9

### Describe the problem

When starting start.sh the terminal prompts "npm is not installed. Do you want to install nodejs and npm? (y/n)"
npm --version says 10.2.4

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
You can avoid start.sh entirely and just use `npm i && npm run start`

**Comment by Viking1811** [comment]
> You can avoid start.sh entirely and just use `npm i && npm run start`

Sorry, I'm relatively new with scripting in Linux. How do I need to rewrite my starter script to do that? The line currently looks like this:
gnome-terminal --working-directory=/mnt/Path/To/SillyTavern-1.11.0/ --e ./start.s

**Comment by Cohee1207** [comment]
Try replacing the last part that calls start.sh with that, escaped with quotes.

**Comment by Techbane** [comment]
Same version of Linux, same issue here. I managed to dig into launcher.sh and find the relevant line despite it being a bit different now and also being split across multiple use cases:
```
case $(basename "$detected_terminal") in
    "gnome-terminal")
        "$detected_terminal" --working-directory="$st_install_path" -- bash -c "./start.sh; exec bash" &
        home
```
And if I'm understanding correctly I should change it to something like:
```
case $(basename "$detected_terminal") in
    "gnome-terminal")
        "$detected_terminal" --working-directory="$st_install_path" -- bash -c "npm i && npm run start; exec bash" &
        home
```
But regardless of what variant I attempt on that, it just kicks back `bash: line 1: npm: command not found
` and aborts the script. Which seems odd because, as ever, npm is very much installed and I can call it from the CLI in the same window immediately after the script tells me it's not found.

**Comment by Cohee1207** [comment]
@Techbane  
Please move the launcher discussion here: https://github.com/SillyTavern/SillyTavern-Launcher
