### ISSUE TITLE
[BUG] Chat Completion Preset overriding Proxy Presets's api information.

### ISSUE THREAD

**Issue by imesha10** [SillyTavern/SillyTavern#1839]
### Environment

Self-Hosted (Bare Metal)

### System

Windows 11, Chrome

### Version

SillyTavern 1.11.4 'staging' (ec826450)

### Desktop Information

Node JS: v18.15.0
Chat Completion Source: OpenAI - Proxy Presets
Branch: Staging
Model: any gpt version

### Describe the problem

My API key would sometimes change so I would update it in my proxy preset and press save. Then when I switch back to another chat completion preset the old key would be used still.

After investigating it seems the "Chat Completion Preset" json seems to have the old proxy information embedded in them so when they are loaded they override the current one in "OpenAI -> Proxy Preset".
``` json
    "reverse_proxy": "https://api.asdfasdf.app/v1",
    "proxy_password": "asdfasdf-asdf234234",
```

In order to get around this I would just switch to none and back to my proxy preset and hit the save icon on the proxy preset and it seems to update it inside the chat completion preset file.

I think this is a bug but it might be expected behaviour.
The way I expect this to work is that the "Chat Completion Preset" and "Proxy Preset" are separate.
The "ChatCompletion Preset" should not have they information regarding the api base and key and only deal with the generation information and prompts.
The "Proxy Preset" should exclusively handle all the proxy api base url's and keys.

### Please tick the boxes

- [X] You have explained the issue clearly, and included all relevant info
- [X] You've checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] You've checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by cunnymessiah** [comment]
> I think this is a bug

correct

i think it's time we merge #1779 @Cohee1207

**Comment by Cohee1207** [comment]
I'm purposefully avoiding touching anything related to proxies. This PR still leaves a question of migrating user data from setting presets into the new proxy presets.

I don't want to get any more angry comments from hyperobsessed individuals that this broke everything and they've lost their data.

**Comment by Cohee1207** [comment]
Also, the PR does more than requested here, by also saving the model and source into the proxy preset. We're once again running in circles, so I'm not merging until everyone settles and agrees on what they want in all meticulous detail.

**Comment by Cohee1207** [comment]
Sorry, took more time to read through it once again and saw the part that saves the model and source is actually optional. Then I guess the only thing to handle is data migration, and it's good to go. If you don't want to make it automatically - how about making it a button-activated action @kingbased ?

**Comment by cunnymessiah** [comment]
the only problem with having the program do migration instead of the user is that i don't know how the naming of the preset would be handled. the name of the proxy can't just be gathered from the URL because most proxy url's are unrelated to the proxy name (proxies hosting through trycloudflare for example), so what would the preset be called? there has to be some form of user intervention to actually name the preset.

my idea was to just leave the proxy url/password field in the chat completion file untouched, it wouldn't be modified or loaded from, it would just stay there for archival purposes in the case someone did end up permanently losing their proxy password. that way they could just be pointed to opening up their chat completion preset in a text editor and retrieving the password from there and then do the manual migration like everyone else.

either way, the preset update has been in sillytavern for a while now, i think most people who care would have already set up their proxy presets by now. the archival idea was just for the very few who completely lost their token (not very likely with how tokens are usually given out through email) and haven't used ST in a while

**Comment by imesha10** [comment]
@kingbased I don't have that much context to this dillema about loosing api info but is this a possible solution.

1. Detect if the current chat completion preset json has the api info keys when loading it.
2. 
    a. Then if it does have the api info, load up the fields so that people who has it there can use it. (If they later decide to empty the field, the next time it is loaded up it would go back to not showing the fields)
    b. If there is no api information then don't have the fields cause it looks nicer and it creates a good seperation between the sections. It will also force new users to use the new system which I think is a better.

Just thoughts....

**Comment by Cohee1207** [comment]
The name of the migrated proxy is the least concerning part and the solution seems simple - `Setting Preset Name (Proxy)` - the last part being literal, and the first part variable. The next logical step is to apply deduplication and pruning in case some of the presets used the same proxy (or none at all) or the preset proxy is already saved.

**Comment by imesha10** [comment]
Now that I have gotten used to this, I think this is not a problem. I'm closing this. Maybe it's useful to refer to what proxies were used a long time ago, and it's not too much of a hastle to go to "None" and select the current proxy.

Maybe an "Always override proxy preset password" option in the main proxy connections menu.
