### ISSUE TITLE
[FEATURE_REQUEST] Squash assistant messages together for group chats

### ISSUE THREAD

**Issue by Memerlin** [SillyTavern/SillyTavern#1919]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

When using Claude 3, either Sonnet or Opus, if there's two consecutive character replies in context, I get the following error:

**Proxy streaming error (Bad Request)**
The API returned an error while streaming your request. Your prompt might not be formatted correctly.
*AWS validation error: messages: roles must alternate between "user" and "assistant", but found multiple "assistant" roles in a row*

### Describe the solution you'd like

We can already squash multiple system consecutive messages together. Doing the same with assistant messages could fix it. It could be a toggle too.

### Describe alternatives you've considered

I've tried putting the messages together and, while it works, it looks ugly and it kind of defeats the purpose of group chats.

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

None

**Comment by Cohee1207** [comment]
Assistant messages are squashed, as well as user messages: https://github.com/SillyTavern/SillyTavern/blob/staging/src/endpoints/prompt-converters.js#L124

It's not an option because as you've mentioned Claude won't allow sending prompts with non-alternating roles. I think the problem in your case with groups is that the completion should end with a user message, which is perfectly achieved using a "Group Nudge prompt template" utility prompt which is inserted at the end of completion. With this config groups are functional for me with Claude 3.
