### ISSUE TITLE
[FEATURE_REQUEST] Add installation guide with Docker

### ISSUE THREAD

**Issue by GalileoFe** [SillyTavern/SillyTavern#1945]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

The author has provided the Dockerfile and docker-compose file in the GitHub repository and published the image on Docker Hub. However, there is no mention in the README that the software can be deployed using Docker. This behavior can confuse users. I spent a long time last year looking for a tutorial on deploying with Docker but couldn't find any. This year I searched again and still found no relevant information online.

### Describe the solution you'd like

I think an "Installation Guide with Docker" section should be added to the README, telling people how to deploy the software using the provided Dockerfile and docker-compose, with some necessary explanations and example commands. This would be convenient for users who want to deploy using Docker.

### Describe alternatives you've considered

There are no alternative solutions at the moment. Adding a Docker deployment tutorial to the README is the most direct and effective solution.

### Additional context

None

### Priority

Medium (Would be very useful)

### Is this something you would be keen to implement?

Yes!

**Comment by bpawnzZ** [comment]
I cant get it working properly using docker either.  I think docker is broken

**Comment by Exemocaro** [comment]
I fixed the docker installation command, at least on Windows. The command I used is the following. Beware that I modified it so that it creates and runs the container, and it will also run every time you turn on Docker Desktop. paste the following on cmd, but change your timezone (or remove it, I don't think it matters anyway):

`docker run -d --name sillytavern -e TZ="[TimeZone]" -p 8000:8000 -v sillytavern-plugins:/home/node/app/plugins:rw -v sillytavern-config:/home/node/app/config:rw -v sillytavern-data:/home/node/app/data:rw --restart always ghcr.io/sillytavern/sillytavern:latest
`

EDIT: After installing it, it probably thinks the local machine is a remote host because I'm getting a "Forbidden: Connection attempt from 172.17.0.1. If you are attempting to connect, please add your IP address in whitelist or disable whitelist mode in config.yaml in root of SillyTavern folder."

**Comment by Cohee1207** [comment]
Already exists.
