### ISSUE TITLE
[Feature Request] Prompt triggered by specific inputs

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#1997]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I would like to be able to set conditions for some prompt to be triggered, so that the prompt is only passed into the ai model if the input satisfies a specific regular expression.
If you have such a feature, ai don't have to deal with all the character prompts every time, and we can save more context length.

### Describe the solution you'd like

sth like:
```
{{If match (regex here)}}
Xxxx
{{Else}}
Xxxxxx
{{Endif}}
```

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

None

**Comment by LenAnderson** [comment]
World Info does matching by keywords instead of regex (and other stuff like chars, inclusion groups...) but seems to be pretty much exactly what you're asking for.

**Comment by steve02081504** [comment]
> World Info does matching by keywords instead of regex (and other stuff like chars, inclusion groups...) but seems to be pretty much exactly what you're asking for.

But as far as I know that's for providing a setting for the worldbackground, and I'm trying to be selective in the character prompt and sample dialogue.

**Comment by LenAnderson** [comment]
The name "World Info" is misleading. It's just the most flexible tool that gives you the most control over how to build your prompt. What to include, and where, and when... Think of the World Info feature as a very powerful prompt builder.

There is absolutely *nothing* special about any of the differently named fields (character description, sample dialogue, personality, scenario, author's note, world info...) all over ST. In the end, all the LLM sees is just a wall of text.

Have a look at what actually gets sent to the LLM in the SillyTavern console / shell / cmd window. At best you have something like "Alice's Persona:" in front of the character card's persona description. Nothing you could not do with an entry in a WI book.


My character cards are completely empty, as is my "jailbreak" and "NSFW" prompt and "Main Prompt" etc. I have all of that in World Info because nothing else give me as much control over where things go (and when they are included in the prompt) as that.

**Comment by steve02081504** [comment]
got it, thx for your help!
