### ISSUE TITLE
[BUG] Unexpected execute on AI message when swiping

### ISSUE THREAD

**Issue by creamsan** [SillyTavern/SillyTavern#2095]
### Environment

📱 Termux

### System

Mull 124.2.0

### Version

SillyTavern 1.11.8 'staging' (f1c96eb6)

### Describe the problem

QR triggers at beginning of AI message on swipe. Expected to trigger only at the end.

### Additional info

A simple echo qr with the following checked.
![Screenshot_20240416-101245_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/ef5bd81e-d7f6-4abb-b503-835314002b30)
On swipe.
![Screenshot_20240416-101448_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/525abe29-f274-44cb-8ba9-27199fda5902)
![Screenshot_20240416-101511_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/f70985e7-bffb-4736-8a02-edb65270defa)

Also happens with continue.
![Screenshot_20240418-101343_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/c87701ac-5b18-4bcf-9654-e8a26a4a7144)
![Screenshot_20240418-101404_1](https://github.com/SillyTavern/SillyTavern/assets/141376415/bf450d63-bc9c-430c-bc63-c39a77d3e231)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Are you in a normal chat or a group chat?
I checked the code and this should not really happen. Swipes are not treated differently than any normal message is, so either the behavior is the same for both or not.  
Maybe I am missing something.

**Comment by LenAnderson** [comment]
@Wolfsblvt 
> Swipes are not treated differently than any normal message is

They are, though. In a way.

This is probably related to the double sending of the char message rendered event. Happens when streaming is enabled. And only on swipes/continues. Because cohee had added checks to regular replies at some point but not to swipes and continues (and can't tell you why not).
First time the event is raised is when the "..." is placed in the message IIRC. This event should not exist, but *maybe* some other extensions / plugins rely on it (cohee mentioned translations). I did not want to deal with enabling compatibility for extensions relying on what is essentially a bug, so I stopped there.
And I'm not going to put a dirty workaround like checking if the current message is "..." into QR (I think that's what the old QR implementation did to deal with the event bug).
Either someone fixes the events, or puts the dirty hack or some other workaround into QR. But it's not going to be me.

I raised that issue shortly after QR overhaul. Then again a while later. But nobody was willing to touch it and investigate potential side effects from removing the incorrect event... so it just kinda stayed as is. Actually, someone even *added* another event to ST, just to avoid touching this.

https://discord.com/channels/1100685673633153084/1180618204238848050/1193672500169674822
https://discord.com/channels/1100685673633153084/1100820587586273343/1200171125787865200

**Comment by Wolfsblvt** [comment]
Man, that's ugly. And nah, sorry, not gonna touch this either. Generate method and all its quirks and events is far too much over my head for now. Got enough on my plate.

So yeah. Bug and likely not fixable unless Cohee takes this up.

**Comment by Cohee1207** [comment]
@Wolfsblvt 
You're right, the problem is that swipes emit a `MESSAGE_RECEIVED` event when a new swipe is requested. And yes, it's up to the event consumer to handle that and skip events for messages with the "..." or empty content - most of them do, like translations, TTS, and apparently old QR. So it's really as simple as adding this check back.

**Comment by Cohee1207** [comment]
> And I'm not going to put a dirty workaround like checking if the current message is "..." into QR (I think that's what the old QR implementation did to deal with the event bug).

I took that liberty since it's pretty much a common pattern for all listeners of this specific event. There might be legitimate use cases when you want to track when the swiped message was updated with the first chunk of the streamed generation, so I'm not going to suppress that emission across the board.
