### ISSUE TITLE
[FEATURE_REQUEST] optional saving card as yaml+plain png

### ISSUE THREAD

**Issue by steve02081504** [SillyTavern/SillyTavern#2128]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

I'm trying to create git repos for some of my complex cards, but ST defaults to storing them as PNG+Metadata, which isn't very conducive to version tracking and many of git operations

### Describe the solution you'd like

It would help a lot if there was an option to store some cards as well-formatted yaml files + plain png by default

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by ghost** [comment]
I want to add on to this that storing anything meaningful in metadata on an image is very dangerous because a lot of software quite carelessly erases or modifies metadata in ways that can break it.  Metadata in an image can be useful but should be treated as volatile overall.  In very rare cases, some image viewers have been known to modify metadata even just previewing an image.

There are also rare cases where one might want to modify character data externally (for example, I've run into a few cards where if I open the advanced definitions to try to edit creator's notes (necessary for Chub imports since the top line does not get imported leaving a blank line in the character list rather than character info) it actually made a copy of the card instead of editing.  Editing externally of course could fix this (albeit inelegantly.)

**Comment by Cohee1207** [comment]
The change of data format store is not planned.
