### ISSUE TITLE
[FEATURE_REQUEST] Option to disable character's first message.

### ISSUE THREAD

**Issue by africsnail** [SillyTavern/SillyTavern#2188]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

It would be nice to have an option to completely disable character's first message, so you can start the conversation yourself or just send blank message for the first message to be generated. 

### Describe the solution you'd like

I think that the default _'Hello'_ message is unnecessary and if left blank, there should be no first message. Other option is to make this some kind of optional checkbox in the character configuration.

### Additional context

This can currently be done by not including the first message in prompts (the "eye" button), or by deleting the first message.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
`/cut 0`

**Comment by africsnail** [comment]
> `/cut 0`

Sure, another workaround. 

Also, when you remove it and don't write the first message in the chat yourself (you just click send without writing anything), the first message can't be regenerated using the arrow button. It just shows the same message again. You can still regenerate using "Regenerate", but that way you can't go back to the previous versions as with the arrow buttons.

**Comment by Wolfsblvt** [comment]
Write a QR that runs on chat open/creation and hides or deletes the first message. That's really easy to write as a script and you don't even need to type it manually. It'll happen automatically.  
You can also write it in a way that it only deletes/hides the first message if it was empty in the character card.

That's what STscript is for actually - because not every specific edge-case can or should be a UI setting or work by default.

ST is very powerful and you can easily customize it how you want (:  
If you need help with writing that script, there are helpful people on the Discord who can answer your questions.

**Comment by africsnail** [comment]
Well, thanks for the tip. 

My point was that this would make sense as a default or at least as an option, but I am aware that it's just my point of view.

**Comment by Lissanro** [comment]
As an idea how to implement this feature without adding an explicit option, I can suggest to automatically disable the first message if the "First message" field is empty, since in this case it is clear that the user does not want any greeting message. Currently if I leave it empty, it forces generic "Hello" message (instead of disabling sending the first message, which is what I intuitively expected would happen if I leave it empty).

**Comment by Cohee1207** [comment]
> As an idea how to implement this feature without adding an explicit option, I can suggest to automatically disable the first message if the "First message" field is empty, since in this case it is clear that the user does not want any greeting message. 

This is done.
