### ISSUE TITLE
[BUG] <Auto Generation of XTTS in Silly Tavern>

### ISSUE THREAD

**Issue by KazPulse** [SillyTavern/SillyTavern#2192]
### Environment

🪟 Windows

### System

Google Chrome 121.0.6167.161. Windows 10 Pro. i7-13700K. 3080ti. 

### Version

1.11.8

### Describe the problem

A question about the work of XTTS in SТ.
The bot's response language is English. Then the translation into Russian is carried out via Google translate.
Due to the peculiarities of translation, the signs "" change to «».
I change them back to "" via regex.
Apparently, for these reasons, XTTS does not start automatic voicing of the replica.
Is there any way to fix auto-generation?

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by KI-DAP** [comment]
Hello, this information might help with troubleshooting. I have the same problem when I translate from English to German.(google).

 Then the Text-to-Speech function (TTS) does not work because “Narrate only the translated text” is clicked.
As soon as I remove the checkmark, TTS works, but only for the English text, not for the translated one.

Windows 11, RTX 4080, 32gb ram , Edge Browser

Have a nice day

**Comment by Cohee1207** [comment]
Found the problem. Should be fixed in staging.
