### ISSUE TITLE
[BUG] Chat formatting not displayed correctly when wrapped between tags.

### ISSUE THREAD

**Issue by JanMyst** [SillyTavern/SillyTavern#2210]
### Environment

📱 Termux

### System

Firefox iceraven-2.14.0

### Version

Bug started from staging (https://github.com/SillyTavern/SillyTavern/commit/be4637a3a0b6e1ebc8766e6fa9ac48297d51a808)

### Describe the problem

Text formatting is incorrectly displayed when wrapped between any tags when the `Show <tags> in responses` is disabled, it squishes separate lines together into a block of text.

Examples:

Before bug:
< Tags >
Text1
Text2
Text3
< /Tags >

After bug:
< Tags >
Text1 Text2 Text3
< /Tags >

### Additional info

Here are some screenshots showing the bug

Before bug
![Screenshot_2024-05-10-19-37-21-554_io github forkmaintainers iceraven](https://github.com/SillyTavern/SillyTavern/assets/169449870/9f3302f0-a7d3-43e6-bbd7-e2ab42a04ea8)

After bug
![Screenshot_2024-05-10-19-35-08-851_io github forkmaintainers iceraven](https://github.com/SillyTavern/SillyTavern/assets/169449870/48a42765-2fd5-4317-b94b-d2b4829c1979)

With the `Show <tags> in responses` enabled in both instances.
![Screenshot_2024-05-10-19-38-46-457_io github forkmaintainers iceraven](https://github.com/SillyTavern/SillyTavern/assets/169449870/463f473a-2490-4c44-a8a8-55e77e28ce0b)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
Previously all newlines were forcibly converted into `<br>` tags, which causes problems on Safari which renders `<br>` as a full-sized block instead of a single line break, not to mention messy markup with tons of line break blocks in result.

The problem with pseudo-HTML blocks is that they display a single P-block upon sanitation and rendering which collapses their internal whitespace. I added a hacky workaround to replace `\n` with `<br>` again, but only inside of unknown HTML elements that are not part of the spec. List here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by JanMyst** [comment]
Well that's sucks, I guess I have to use a workaround for it. Thanks for fast reply!

Something I found that works:

`<Test>`
`<div style="white-space: pre-wrap;">`
Text1
Text2
Text3
`<div>`
`</Test>`

**Comment by Cohee1207** [comment]
A custom CSS may also help
```css
.mes_text p {
  white-space: pre-wrap;
}
```
