### ISSUE TITLE
[FEATURE_REQUEST] quick impersonate/regenerate and adding swipes to persona message

### ISSUE THREAD

**Issue by etgv2** [SillyTavern/SillyTavern#2232]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

Unable to swipe on persona messages.

### Describe the solution you'd like

There is a quick continue button, so I think there should be a quick regenerate and quick impersonate button, I would use this feature alot. I use multiple personas in one chat and use impersonate often, so being able to swipe on messages sent from my persona characters would be useful for me as well.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Wolfsblvt** [comment]
For continues, there is an extension that is swipe-like: https://github.com/LenAnderson/SillyTavern-MoreFlexibleContinues
Buttons can you are asking for can be done via QR buttons if you just call `/regenerate` and `/impersonate`.  
Pretty sure Lenny also had an extension where you can add swipes to a user message via script iirc. So that could also be scripted.

**Comment by etgv2** [comment]
I tried to add the link "https://github.com/LenAnderson/SillyTavern-MoreFlexibleContinues/" to the extension installer, but it didnt work. It says problem with assets url, pls help.

**Comment by etgv2** [comment]
i saw he does have a user swipe extension like that but it dont work sadly :( I wish i knew how to make extensions
