### ISSUE TITLE
[BUG] <title> When importing chat completion preset file, reverse proxy information from file provider will also be imported

### ISSUE THREAD

**Issue by yca321** [SillyTavern/SillyTavern#2413]
### Environment

🐧 Linux

### System

Ubuntu, Windows

### Version

release 1.12.1

### Describe the problem

I shared my own chat completion preset to others. When they imported the file I created, they also received the private info such as my own Reverse Proxy URL and Password. 

I am running my silly tavern on an ubuntu server, I also tested this myself by downloading and run a new empty sillytavern on my windows local environment. Imported my own chat completion preset file. And I found my own proxy URL and password on the new sillytavern imported with the file.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Wolfsblvt** [comment]
Not sure if this isn't intentional. Because those are saved as part of your preset.  
If you export and import it for yourself, you **want** those to stay. Understand the security issue though.

I think this is something @Cohee1207 has to say what to do.

**Comment by Cohee1207** [comment]
All is by design. Remove it manually from the exported file if it is a problem or use a custom API type that hides the password in secrets.

This is likely to stay as wontfix since the reverse proxy part never gets any improvements from the main development team besides keeping it minimally working.

One thing I can suggest to external contributors who might attempt to fix it - remove it at export time (for external use), but leave it on save (for internal use).

**Comment by Cohee1207** [comment]
Addressed in release 1.12.4. You now have an ability to discard proxy/custom endpoint data on import or export.
