### ISSUE TITLE
[FEATURE_REQUEST]  keep context on server-side (do not reload with each message)

### ISSUE THREAD

**Issue by sss123next** [SillyTavern/SillyTavern#2519]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

with current design of `SillyTavern` using `llama-server` performance is lack behind `llama-cli` drastically .

### Describe the solution you'd like

i am using llama.cpp.
in my case most of calculations is done during setting context.
i may be wrong.
using `llama-cli` i can set context via first message or even text file, and after this it starts to generate responses to new short message nearly in no time, in contrary using `SillyTavern` via openai api with `llama-server` seems setting up whole context from zero with each new message from user, and setting context is taking most resources, so i guess if it is possible to set context just once for chat session will speed up whole thing a lot.

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
Please don't use the llama server with the OpenAI endpoint, it is highly suboptimal for text completion models due to the double conversion of prompts. Switch to text completions which provide native support for the llama server with much more settings and prompt formatting options. Also, make sure the context doesn't change between the prompts, this is possible to do on staging in the prompt itemization window which highlights the diff between the prompts.

**Comment by sss123next** [comment]
thank you for clarification, and sorry for stupid question.
