### ISSUE TITLE
[FEATURE_REQUEST] Allow Changing of API Endpoint for Free Mode Prompt Extension in Image Generation

### ISSUE THREAD

**Issue by RicedOutDesktop** [SillyTavern/SillyTavern#2538]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I have a local model running that does a better job at describing the context of "Last Message" for image generation, however I use a proxy endpoint for the main RP context. Having the option to make "Extend free mode prompts" use its own endpoint would save some steps in switching the connection for every image and streamline the experience.

### Describe the solution you'd like

When selecting the "Extend free mode prompt" option under Image Generation it would be useful to have an option to select another endpoint apart from the currently selected API connection.

### Describe alternatives you've considered

1. Keep switching the API connection when wanting to generate an image.
2. Enhance the image generation prompt to perhaps get close to the local model

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
This is architecturally impossible due to how ST treats model connections. What you mean by "allow changing the endpoint" actually implies a lot more than that: changes to the API endpoint, model name, formatting rules, sampling parameters, context size, prompt set, etc. API connections are very dependent on what is currently chosen in the UI.

What you're asking for is usually achieved by using STscripts to change model/settings/etc., trigger an extension (image gen in your case), and then switch back. Very rudimentary example below. Fill it out with your desired configuration and add this as a Quick Reply button.

```
// save current values |
/api | /setvar key=saveApi || /preset | /setvar key=savePreset || /model | /setvar key=saveModel ||
// set your preset, model, api here |
/api claude || /preset Default || /model haiku ||
// get SD freemode prompt and generate |
/input What to generate? | /sd {{pipe}} ||
// restore previous values |
/api {{getvar::saveApi}} || /preset {{getvar::savePreset}} || /model {{getvar::saveModel}} ||
// unset variables |
/flushvar saveApi || /flushvar savePreset || /flushvar saveModel ||
```

**Comment by RicedOutDesktop** [comment]
I see, that's truly too much for a simple QOL change, haven't delved into the codebase too deeply...
I'll just close this myself, then.

Thanks for the quick response, I'll get to work on the STscript Quick Reply.

Cheers!
