### ISSUE TITLE
[FEATURE_REQUEST]  Allow for back and forth "user:" "char:" format, by making `\n{{user}}` stop string optional.

### ISSUE THREAD

**Issue by Notiee** [SillyTavern/SillyTavern#2556]
### Have you searched for similar requests?

Yes

### Is your feature request related to a problem? If so, please describe.

I've always preferred how JanitorAI does conversation, basically interpreting the user's prompt and narrating a story or scenario from that. I find that it's more fun and engaging seeing what the LLM comes up with this way, and it's less writing from my end, just letting the card and a few words create believable role-plays.  

I also really like the format:
```
name: "response"
name2: "responds back"
name: "continues conversation"
name2: "etc"
```
![Screenshot 2024-07-25 150608](https://github.com/user-attachments/assets/7ebf3e2c-12f7-44b8-b51a-ec88c9d100a4)

which currently isn't possible (to my knowledge, I'm a beginner here) with the current way SillyTavern sets it's stop strings.

I've been trying to emulate Janitor style conversations with SillyTavern but because `\n{{user}}` always shows up in the stop strings, it stops before the narration lets my persona respond. 

Altering the `getStoppingStrings()` function to return a fugazi string[] (`[\nTest1]`) allows me to achieve what i want: 
![Screenshot 2024-07-25 151810](https://github.com/user-attachments/assets/cf203b54-958e-4e70-a396-67b38381f011)

### Describe the solution you'd like

It would be nice to have it be optional in either the Advanced prompt format or Sampler settings. 

### Priority

Low (Nice-to-have)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by Cohee1207** [comment]
With how often "HOW TO MAKE THE BOT NOT SPEAK/ACT FOR ME" is being mentioned (some models are just prone to impersonation and will do that unprompted), I doubt this is a top priority for us to allow the exact opposite. But may considered as a checkbox somewhere in the formatting settings.

**Comment by JPFlare** [comment]
FWIW this has been plaguing me as well. I've been using sillytavern for months, and couldn't figure out why it would suddenly stop for seemingly no reason. I removed everything from stop strings, banned eos token etc, but it was still stopping. Eventually I noticed in the console that for some reason the name of my persona was still a stop string, and there is no option to disable it. I googled for hours to find something, and after struggling with it again today, happened to find this post from another person having the same issue, despite how obscure the issue is. In my opinion, it makes no sense to have a default stop string that you can't remove, especially when there is a use case for not having it enabled that is directly related to the intended purpose of sillytavern.

I would be super grateful if you could consider allowing us to disable it, as I ran into this almost immediately upon using sillytavern for the first time, and it has been an issue ever since. Since the AI can and will sometimes stop generating responses when it thinks the message should end, it's easy to confuse that with what's happening here. I've run into this with plenty of situations, most recently when using a character to help generate other character cards. When I ask it to generate example dialogue that would be included in the character card, it often uses the format that is most common, which is to have the name of the character followed by a colon, which makes it inevitable that you would run into this.

Please reconsider the low priority tag, though I do understand if your opinion of the problem is different from ours, and still decide to have it on the backburner.

Regardless of the outcome, thanks for considering it.

**Comment by Cohee1207** [comment]
To allow explicit display of impersonation in replies, apart from the new toggle in staging, you've got to enable both: 
1. Show {{char}}: in responses
2. Show {{user}}: in responses

**Comment by JPFlare** [comment]
Wow, that was incredibly fast. Thank you so much for reconsidering it, I really appreciate it.

Do you mean that when the new toggle is available, you'll have to enable both of those options?

I'll make a note for myself for when the toggle goes live, so that I know how to enable it in the future.

Thank you again!
