### ISSUE TITLE
[BUG] Lorebook Trigger probability not calculated correctly?

### ISSUE THREAD

**Issue by Susanoo1337** [SillyTavern/SillyTavern#2771]
### Environment

🪟 Windows

### System

Windows 10, Firefox 115

### Version

1.12.5

### Desktop Information

Branch [timed-effect-groups]

### Describe the problem

Given the issue #2762 I've been trying to construct a workaround and noticed unexpected behavior:
Given 6 entries in a group with the following trigger probabilities and order numbers (all on the same trigger, all group weights 100):
Entry 1 Order 99 80%
Entry 2 Order 98 75%
Entry 3 Order 97 50%
Entry 1a Order 96 99%
Entry 2a Order 95 99%
Entry 3a Order 94 99%
("a"-series entries are duplicates of the original entries with 99% probability as a fallback for the 2.5% odds that 1,2 or 3 don't get picked)

Expected behavior:
ST should check the entries in order and move on to the next if it doesn't trigger.
The odds of no entry in the group triggering would be 0,2x0,25x0,5x0,01x0,01x0,01=0,0000025 or 0,00025% which might as well be 0.

Observed behavior:
In 100 rolls the following entries were triggered in % (with expected odds):
Entry 1/1a 32% (82,475%)
Entry 2/2a 26% (15,02475%)
Entry 3/3a 18% (2,5%)
NONE 24% (0,00025%)

(Addendum: Even with one of the entries set to 100%, and strategy set to constant, sometimes no entry will trigger. Even if I'm wrong about order and trigger chance, with at least one entry set to 100% "no entry" should never be the expected result. My lore budget is 4096 tokens)

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
> ST should check the entries in order and move on to the next if it doesn't trigger.

We might have conflicting opinions on what is the expected behavior, but right now - it is not how it works. All trigger% probabilities in groups are independent and calculated first before going into group filtering stage. Next, entries that are left after the keyword/trigger filters are filtered (optionally, if enabled) with key matching score, and then every group entry is weighted using the group weight (independent of trigger%!) against a random value to have only one winner in result.

> Even with one of the entries set to 100%, and strategy set to constant, sometimes no entry will trigger. 

Even constant entries could be filtered out if they're group losers. Constant in reality means that it skips past the keyword checks. All additional filters (probability, groups, etc.) might deactivate the constant entry.

Lorebooks/WI checks have greatly detailed logs accessible via browser's DevTools. If you have any doubts on why a specific entry was or wasn't activated, open DevTools Console, enable Verbose logging level there and filter logs by the `[WI]` prefix.

@Wolfsblvt pinging in case you have anything to weigh-in.

**Comment by Wolfsblvt** [comment]
Yup, this is not the expected behavior. Maybe it's not documented ideally. But documenting the deep depths of WI and combination of different settings you can add is very, very hard. If you have any improvements to the docs, let us know.

Cohee already explained it well. Important to note is:
- **Constant** => Skips keyword checks (can still roll probability or be excluded by budget, groups, etc)
- **Inclusion Groups** => After matching (NOT activating), filter out all but one entry. This means after keys/constant are matched, before probability and budget is used.

In summary, Inclusion Groups are used to only allow one entry to go through to the actual activation check, **if** there are more than one who are possible candidates, because of their match checks.
If multiple entries are in a group, they get weighed against each other via scoring (if you have that enabled), or via the **Group Weight**. That is actually what you likely want to use, instead of the trigger%.
The trigger% literally just means "hey, if matched and decided this should be part of the context, roll a percentage if really".

You can achieve what you want to weighing the group entries against each other via group weight. And if you still want to keep situation where no entry is triggered either set them all with a high trigger%, or just add an empty entry to the group with a specified weight, that might be rolled for the group and then lead to nothing being inserted.

WI is powerful, and most scenarios are already there. It's just hard to get around the *how*.

**Comment by Cohee1207** [comment]
My original intention behind introducing Inclusion Groups might be a good starting point for understanding a general idea behind them. It was already specified in the documentation, but let's just reiterate on it as real life examples are easier to follow than purely algorithmic explanations.

Let's imagine I have a musician bot with a lorebook of 50 song lyrics that are all activated by the keyword `sing`. Normally, when I tell it to `sing me a song`, it might pull all 50 entries into the context. But if I put these entries into a group 'songs', then only one of them will be pulled when I ask to sing a random song. Added functionality like weights give certain entries more priority in the random selection (`sing your favorite song`), and key scoring prioritizes certain entries  if I mention more keywords compared to the others (`sing a specific song`).

**Comment by Susanoo1337** [comment]
So if I understood this correctly, (and assuming all entries are constant to skip the keyword phase - that much I had figured out beforehand, I just mentioned it to make sure it doesn't seem like I overlooked a step with the keywords during testing)
1. Since all entries are constant, they go straight to the group filter.
2. One winner goes on to the trigger check
3. If the winners trigger chance is only 50%, it might still not get picked, and no insertion happens until the next attempt?

Can you really quickly tell me what kind of weight system it is? I.e. If I have only two entries, with the weights 100 and 50, is it the same as 10 and 5? Or how is the winner calculated?

I really expected the order to the reverse of that.
The reason I had set up trigger % was because groups with group weights that were not all 100 seemed to ignore sticky. The random entry selection worked great with group weights otherwise, just not usable without sticky. (but I opened a different bug report for that already)
Once I have time I'll delve into the DevTool mode to try and get a solid grip on the system, and get back to you about improving wording/clarity in the docs.

Anyway, thanks for the explanation.

**Comment by Cohee1207** [comment]
> So if I understood this correctly, (and assuming all entries are constant to skip the keyword phase - that much I had figured out beforehand, I just mentioned it to make sure it doesn't seem like I overlooked a step with the keywords during testing)

No, you got the order wrong. Trigger chance goes first, then the group selection phase.

> If I have only two entries, with the weights 100 and 50, is it the same as 10 and 5? Or how is the winner calculated?

Assuming you got only two entries in a group, these numbers would lead to identical results. Group weight is a probability of the entry to be selected in a group compared to the others (the absolute value doesn't matter as total probability is a sum of all weights). If one entry has a weight of 5, and the other one has 10 - the last one would be twice as probable to be chosen. This value is fully independent from trigger%.

**Comment by Wolfsblvt** [comment]
> No, you got the order wrong. Trigger chance goes first, then the group selection phase.

Hm?
Am I overlooking something or misunderstanding something?

![image](https://github.com/user-attachments/assets/87c8cc07-2ebb-417b-9941-ab732681dc2c)
