### ISSUE TITLE
[FEATURE_REQUEST] NovelAI Erato Support

### ISSUE THREAD

**Issue by TimCollins31** [SillyTavern/SillyTavern#2894]
### Have you searched for similar requests?

No

### Is your feature request related to a problem? If so, please describe.

No problem.

### Describe the solution you'd like

NovelAI just released their new model, Erato, to Opus-tier subscribers. I'd like to use it with ST if it's available via the API.

### Priority

Medium (Would be very useful)

### Are you willing to test this on staging/unstable branch if this is implemented?

Yes

**Comment by minipasila** [comment]
I noticed this when looking at [the API documentation](https://api.novelai.net/docs/):
"_The Primary API describes actions that our Frontend makes against the NovelAI backend._

  _In general, third-party NovelAI API users should not engage with the Primary API beyond the /ai/ routes._

  _Third-party API users developing user-facing applications must ask for a user's Persistent API token to continue._
  _For security reasons it is not recommended to hold a user's credentials in plaintext._

  _IMPORTANT: Existing and new API users must read the upcoming generation-specific documentation:_

  _Image Generation documentation: https://image.novelai.net/docs/index.html_
  _Text Generation documentation: https://text.novelai.net/docs/index.html_"
  
Not sure if this is a new thing or something important related to NovelAI's current API.

**Edit:** Well it seems to be a new thing "To ensure that all users benefit from these stability improvements, we will be decommissioning Kayra for subscribed API users on api.novelai.net.
Starting from September 30th, 2024, Kayra will only be available on text.novelai.net."

**Comment by Wolfsblvt** [comment]
Is implemented on staging now.

**Comment by Carnyzzle** [comment]
Getting this from the API When trying to use Erato: 
Invalid Request: On September 18th, 2000 UTC we announced CFG Phaseout for websuite users affective immediately and API users effective in 24 hours. If you are using the NAI website please change your preset and reload the page. If you are using a third-party client, change your generation preset to avoid CFG. From now on you will be able to make use of the min_p sampler and the new unified sampler. 

Just turning off CFG in the Sampling doesn't get outputs sent out either.

**Comment by minipasila** [comment]
They have deprecated CFG as of this new model's release. Therefore you can't use it anymore. Their new hardware apparently doesn't work well with it or something.
More info here: https://blog.novelai.net/inference-update-llama-3-erato-release-window-new-text-gen-samplers-and-goodbye-cfg-6b9e247e0a63

**Comment by Carnyzzle** [comment]
yes, the issue is that CFG is still in staging as of right now

**Comment by minipasila** [comment]
When I used the new Preset it seemed to work just fine.

**Comment by Carnyzzle** [comment]
now I see what the problem was, it was still reading my CFG chat setting even though it's off in the new preset.

**Comment by Cohee1207** [comment]
https://github.com/SillyTavern/SillyTavern/releases/tag/1.12.6

**Comment by Dark-Thoughts** [comment]
Am I the only one who gets like almost a 5 second additional text generation delay after the text gen already finished? Is this related to the model? NAI? ST? Like, it generates its reply, finishes it, but the generation timer keeps running for several seconds, stopping you from doing anything during that time.

**Comment by TimCollins31** [comment]
I get that, too, but I just assumed it was endemic to the platform. It's
annoying to say the least.

**Comment by minipasila** [comment]
> Am I the only one who gets like almost a 5 second additional text generation delay after the text gen already finished?

It's due to the model not stopping after generating the character's reply. If you disable streaming you should be able to see the full message it generates in command prompt.

**Comment by Wolfsblvt** [comment]
Yep. This happens if the model writes a stopping string. ST stops "streaming" the content, as it is not supposed to be shown.
Many backends don't support stopping strings for generation though, so there is no other chance then to *let it finish*, and just cut off what was not supposed to be written.

You can verify this by disabling streaming and checking the full reply, as @minipasila said.

A fix for this is... actually changing/fixing your prompting, so the model is not trying to write as you, {{user}}, or whatever not allowed it tries to generate.

**Comment by Dark-Thoughts** [comment]
Disabling streaming shows me the same type of replies, just that I don't see them until it finished generating them fully (and I presume still the additional generation time it takes even after finishing the reply). I'm still using the default Neutral - Chat System Prompt, since I made a new staging instance of ST, but I don't see anything that would tell it to write as {{user}}. In my previous experience with Kayra it was kinda impossible not to have the AI try to respond as {{user}} at times, as the models generally don't really understand the concept of different characters. They just try to continue the story based on their context tokens - including those of your own texts. I don't remember Kayra ever having this phenomenon of generating past its actual reply without actually generating anything.

**Comment by TimCollins31** [comment]
Maybe ST could detect the stopping token as it arrives and stop listening,
letting the model shout into the void?

**Comment by Cohee1207** [comment]
The problem is that Llama 3 tokenizer has different tokens ids for various combinations of newlines and punctuation.
i.e. `\nTest:` and `.\nTest` produce different token sequences.

**Comment by minipasila** [comment]
NovelAI's models don't have a stop token so it doesn't know when to stop generating, it usually keeps generating forever (until it reaches max tokens). Which is fine for generating stories when it can only generate max 150 tokens and on their frontend it seems to figure out when a full sentence has been generated and then stop there. But in the API it doesn't seem to usually do that.

Their frontend has this though
![image](https://github.com/user-attachments/assets/29f4d8d5-9bfb-4473-879b-6d19c9669772)
which seems to allow it to stop generating more tokens after it hits that sequence. Not sure what's the equivalent option on SillyTavern (if there is one).

**Comment by Cohee1207** [comment]
The frontend does the same thing as we do: encodes stop sequences into an array of token ids.
The problem is that stop strings on a Llama 3 tokenizer that start with a newline do not work anymore since many punctuation characters are now merged with a newline that follows them into its own token id.
`.\n`, `!\n`, `?\n`, `"'\n` - those are ALL different token ids.

**Comment by minipasila** [comment]
> The frontend does the same thing as we do: encodes stop sequences into an array of token ids.

It stops it from generating after it hits the sequence, SillyTavern doesn't ever tell the model to stop generating when it detects that the custom stopping string has been given. 

Considering that if you generate a response in SillyTavern and you see it cuts off the generation and then you manually stop the generation and then try to regenerate it'll complain about "Concurrent generation is locked" but on their frontend you can regenerate immediately after it has hit the Stop Sequence. So it seems to stop the generation on the Stop Sequence. Otherwise it would still be generating in the background right?

**Comment by Cohee1207** [comment]
> manually stop the generation

Here's where the problem is: Novel API doesn't support manual stopping of the generation. And the stopping strings don't even trigger because it doesn't generate them - see my attempts to raise a point about newlines messing them up.

**Comment by minipasila** [comment]
I have not noticed any issues with the stopping strings not triggering. They seem to work as intended.

**Comment by minipasila** [comment]
> Here's where the problem is: Novel API doesn't support manual stopping of the generation.
 
There seems to be "stop_sequences" in the API though?
https://text.novelai.net/docs/index.html#/default/post_ai_generate (note they are deprecating the old API api.novelai.net with text.novelai.net)

**Comment by Cohee1207** [comment]
## Staging before https://github.com/SillyTavern/SillyTavern/commit/8344232fe59b2595e0a089bc3ee2550b48178ad2
### Prompt
```
<|startoftext|>[ Style: chat, complex, sensory, visceral ]
***
Cohee: Hi.
Assistant:
```
### Stop strings
`[ 198, 7489, 50153, 25 ]` => `\nCohee:` (check with the [Tokenizer](https://novelai.net/tokenizer))
### Response
```
 Good evening, Miss Cohee!
Cohee: ...
Assistant: Did you need help with anything?
Cohee: I just came by to have a look at the shop.
Assistant: Okay, take your time!
(If you attempt to leave)
Assistant: Thank you, come again!
(Afterwards)
Cohee: Well, I'm leaving. Bye-bye.
Assistant: Come again! Thank you, miss!
(Cohee leaves the store)
***
[ On the Street ]
Man: Excuse me...
```

Note how NONE of the instances of `\nCohee:` in the response triggered the stopping string. It's easy to see if you inspect the tokens in the response
```json
[7839, 11714, 11, 9083, 3623, 50153, 4999, 7489, 50153, 25, 12515, 72803, 25, 14910, 499, 1205, 1520, 449, 4205, 5380, 7489, 50153, 25, 358, 1120, 3782, 555, 311, 617, 264, 1427, 520, 279, 8221, 627, 72803, 25, 36539, 11, 1935, 701, 892, 4999, 7, 2746, 499, 4879, 311, 5387, 340, 72803, 25, 9930, 499, 11, 2586, 1578, 4999, 4444, 1064, 4102, 340, 7489, 50153, 25, 8489, 11, 358, 2846, 9564, 13, 90425, 1481, 9188, 627, 72803, 25, 15936, 1578, 0, 9930, 499, 11, 3194, 4999, 3100, 78, 50153, 11141, 279, 3637, 340, 34184, 58, 1952, 279, 6825, 5243, 1692, 25, 39995, 817, 757, 1131]
```

## Staging after https://github.com/SillyTavern/SillyTavern/commit/8344232fe59b2595e0a089bc3ee2550b48178ad2
### Added stop strings
```json
[ 198, 7489, 50153, 25 ],
[ 627, 7489, 50153, 25 ],
[ 4999, 7489, 50153, 25 ],
[ 5380, 7489, 50153, 25 ],
[ 5736, 7489, 50153, 25 ],
[ 702, 7489, 50153, 25 ],
[ 13220, 7489, 50153, 25 ],
[ 9522, 7489, 50153, 25 ],
[ 340, 7489, 50153, 25 ]
```
### Response
```txt
 Hey!
Cohee:
```

The triggered stop sequence was: `[4999, 7489, 50153, 25]`

**Comment by Dark-Thoughts** [comment]
The changes yesterday after your comment didn't seem to help but I pulled the latest files again this morning and that seems to have fixed it. Very fast and responsive now!

**Comment by Dark-Thoughts** [comment]
Sooo, found this on a [Reddit thread](https://redlib.privacy.com.de/r/NovelAi/comments/1frivuj/erato_sillytavern_whats_your_experience_so_far/lpde4rq/?context=3#lpde4rq).
Based on the comment chain there's supposed to be a specific token (`<|reserved_special_token81|>`) part of preamble for Erato, but isn't? I'm not sure if that's supposed to be before or after the existing preamble tags.

I also noticed that relatively frequently the chat output does the three asterisks ***, followed by what looks similar to the default preamble strings ([ Style: chat, complex, sensory, visceral ]). I'm not sure if that's a config mismatch but it feels like I did not get it, or not that often (someone maybe remembers better than me), before the stop sequence changes.
