### ISSUE TITLE
[BUG] Flux negative prompt 

### ISSUE THREAD

**Issue by Vibecoder9000** [SillyTavern/SillyTavern#2963]
### Environment

🪟 Windows

### System

firefox

### Version

1.12.6

### Desktop Information

newest, windows, forge

### Describe the problem

When flux is loaded under image generation > models, you still have the ability to set a Negative common prompt prefix, which is impossible with flux. This box should be greyed out or removed.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by Cohee1207** [comment]
I don't think there's any way to tell if the loaded model supports negative prompts or not. I don't think that disabling the control based on just the name regex is a good idea either.

**Comment by Vibecoder9000** [comment]
I doubt somebody would load some other model they renamed to "flux-dev-fp8". It is possible through, so maybe a warning?

**Comment by Ph0rk0z** [comment]
Maybe there is an XL or some future model named flux. I also have flux models that can do negative prompt now, they just require many steps. This one: https://huggingface.co/ostris/OpenFLUX.1 

Works in 20-30 steps with the dev to schnell lora and adding negative prompt of "black hair" gave red hair to the output. 2x slower genning because of CFG though.
