### ISSUE TITLE
[BUG] OpenRouter's Grok-2 API issue with role names

### ISSUE THREAD

**Issue by minipasila** [SillyTavern/SillyTavern#2981]
### Environment

🪟 Windows

### System

Brave 1.70.126, Windows 11 Home 23H2

### Version

SillyTavern 1.12.6 'staging' (93137e3e2)

### Desktop Information

- Node.js: v18.17.0
- Generation API: OpenRouter
- Branch: staging
- Model: Grok-2

### Describe the problem

When trying to generate a reply it gives this error message:
```
Chat Completion API
{"code":"Client specified an invalid argument","error":"Only messages of role 'user' can have a name."}
```
To fix the issue you have to disable "Example Messages" from being sent to the prompt.
Error seems to reference these names here:
    {
      role: 'system',
      content: 'Example message user thingy.',
      **name: 'example_user'**
    },
    {
      role: 'system',
      content: "Example message reply.",
      **name: 'example_assistant'**
    },
It also affects "Character Names Behavior" setting if you enable "Completion Object" setting but if you disable it then it will work.

### Please tick the boxes

- [X] I have explained the issue clearly, and I included all relevant info
- [X] I have checked that this [issue hasn't already been raised](https://github.com/SillyTavern/SillyTavern/issues?q=is%3Aissue)
- [X] I have checked the [docs](https://docs.sillytavern.app/) ![important](https://img.shields.io/badge/Important!-F6094E)

**Comment by cloak1505** [comment]
Actually this should be handled by OpenRouter themselves; they're the ones who handle how the name value is handled.

```typescript
      // If "name" is included, it will be prepended like this
      // for non-OpenAI models: `{name}: {content}`
      name?: string;
```
As of writing, xAI has temporarily taken down the models for maintenance.

Edit: `x-ai/grok-beta` no longer produces an error.

**Comment by LurkingLearner** [comment]
I don't actually think this issue is "resolved" per se, but it's worth noting for anyone else having this problem that it's fixable via a configuration toggle.

If you're trying to use Grok's chat completions API in SillyTavern, you'll have to disable `Chat Examples` under `AI Response Configuration` (the farthest left menu at the top of the UI, then scroll to the bottom) as this is at least one place that is inserting the invalid records into the JSON which xAI will return a 400 on.

That's all I had to do to get rid of the error, but it might be nice to have some intelligence or first party support for xAI's expectations when configuring an xAI API connection built into ST.

**Comment by mutoe** [comment]
Same issue here

<img width="466" height="668" alt="Image" src="https://github.com/user-attachments/assets/97aac757-3289-4355-80cf-cc2166f321af" />

**Comment by Cohee1207** [comment]
@mutoe
Enable "Prompt Post-Processing": Merge. It'll remove names from the prompt.
https://docs.sillytavern.app/usage/api-connections/openai/#prompt-post-processing
