### ISSUE TITLE
Pontificating on Strategies for Infinite Context

### ISSUE THREAD

**Issue by digiwombat** [SillyTavern/SillyTavern#376]
This isn't a feature request so much as it's just laying down some thoughts on a way to handle Infinite Context that I may fork and try later (thanks to Cohee and maceter for the excellent work).
 
I'd be interesting to see how effective it would be to adopt a less direct approach to the infinite context problem. I think there is definite value in the token efficiency of the original memory plugin summarizing the chat. I think taking sets of two to three replies and summarizing them, then adding those to the vector store would be of value since it would add a neat, concise summary of the lines into the store. Obviously, this assumes the summary engine is reasonably good at those shorter chunks. The big model could be used for summaries, assuming they would produce better outputs, though things like proxy could get in the way there for people running that and paid API users won't like it I'm sure, so we'll ignore it for now.

So to bullet point it for clarity the idea is something like this:

0. Structure: Two ChromaDB collections (DBs, tables, whatever they call them). One for summaries, on for messages.
1. Every 2-3 messages, summarize those messages AND save the index/id of the messages for more detailed lookup. Summaries will contain more relevant information across multiple messages that can be used as a plaintext memory.
2. When doing a lookup, maybe do a similarity check against the incoming phrase for concepts like "What did you say" to mark looking up specific entries if the Chroma kicks back an entry we want to use. Or, better, use that cue to skip the summary and just go straight to doing a lookup on individual entries. This is a mushy idea. Hard to implement well, I think.
3. Potentially use information from the classify extra to give high emotional events a ranking in the database (could just be a max emotion number that takes the highest classify value, assuming there is confident in those results). This could be used to help order memories across longer time frames potentially. Though recency biasing is also valuable. Some combination of the two would be good.

An alternative for the above would be grabbing multiple relevant entries together and summarizing those, but that runs a big risk of conflating things that happened at wildly different times.

Okay, that's enough vague rambling. I'd welcome any additional thoughts on ways Infinite Context might be made more robust since the memory question is I think a big thing everyone wants to get right.

**Comment by drgnfr6** [comment]
I like the idea of higher emotional value events being tied to greater relevance. It mimics memory processes that will naturally be more human-like. That said, it's often going to be detail that gets us, especially repeated details. I'd think it may help to have a reference outside that contains 3 exchanges (back/forth 3 times) with an assigned ID. Store each exchange individually into a ChromaDB store. On each new exchange, retrieve the _most similar_ exchanges, within some thresholding of minimum similarity. Pull the contextual exchanges (the reference to 3 exchanges, the other two surrounding each directly relevant one). Pass all of this (each relevant exchange, plus the two surrounding it, in temporal sequence, as if it were a chat context itself) to the existing "memory" handler. Store _this_ summary into a ChromaDB that would be searched. Note, this is a _lot_ of handling for the summarizer, chromadb, etc. to be doing, so it might be that it's only done on some kind of keyword recurrence basis or that it's done specifically for the _summary_ of a new 1024 block of context or similar.

In other words, without the suggestion on how to solve, I think there's actually a few problems to solve in terms of memory:
* Emotionally attached memories (I like the suggestion of leveraging emotional weight)
* Repetitive memories (This is what the above tries to solve, though might be too heavy to run constantly)
* Sensory attached memories (not entirely sure how to solve, especially since these are often _very_ detail centered. Maybe through keyword processing combined with subject based recall somehow. My ideal solution would work like it was auto-creating a set of "world" entries with details included for various subjects, situations, locations, etc. Things like hair/eye/skin color for all characters that's automatically remembered for everyone all the time and comes "to mind" whenever they are mentioned)
