### ISSUE TITLE
[QUESTION] Calculation of the tokens in ST 

### ISSUE THREAD

**Issue by Woisek** [SillyTavern/SillyTavern#797]
In the title. How is the token calculation done in ST?
I use the AI Character Editor for creating characters and try to get around 1000 tokens. But it seems, the token calculation from ST is different than from AI Character Editor.
For example, I have a character that has 971 total tokens in AICE, but 1198 in ST.
Could anyone explain how this difference comes and if it's good/bad/whatever, please? 🤔

**Comment by Cohee1207** [comment]
Different models use different tokenizers. OpenAI, Claude, Llama: all count tokens differently. Chat completion API mostly preselect tokenizer automatically. For local you have to figure it out depending on models you run.

**Comment by Cohee1207** [comment]
Pro tip: Character Editor uses GPT-3 OpenAI tokenizer. But there are no local models that use it.

**Comment by Woisek** [comment]
Thanks for your info.

>Different models use different tokenizers.

Does that mean, ST calculates tokens on the basis of the selected (local) model?
And that means further, if I change the (local) model, the token count will change?
Did I get this right? 🤔

**Comment by Cohee1207** [comment]
No, that's the opposite of what I meant. Usually, local API does not provide access to model tokenizers. "Usually" because oobabooga added that recently, the API tokenizer needs to be selected separately. Otherwise, for local meta, the llama tokenizer is the most fitting choice anyway (since models are based on this use sentencepiece tokenizer with llama model).

**Comment by Woisek** [comment]
Ah, okay ... thanks for the explanation. 👍
