### ISSUE TITLE
[Feature Request] character tag aliases/alternatives

### ISSUE THREAD

**Issue by CuddleBear92** [SillyTavern/SillyTavern#802]
**Have you searched for similar [requests](https://github.com/SillyTavern/SillyTavern/issues?q=)?**
Yes

**Is your feature request related to a problem? Please describe.**
Character tags should have aliases/alternative names to merge tags into one.

**Describe the solution you'd like**
For example tags like Female, female, girl, woman, Woman and so on could be merged into just Female. Where there would be a single tag called "Female" then with the additional aliases would be listed and saved under that tag.
This will clean up the tag lists and make it much more useful in the end. 

**Describe alternatives you've considered**
Merge Button to add the alias into the dominant tag.

**Comment by Woisek** [comment]
Why would one tag "Female" and "female"? Or "Woman" and "woman"?
And although woman and girl means similar subjects, I see it still as a difference, a woman is not a girl and vice versa.
So personally I wouldn't merge woman and girl.

Just saying ...

**Comment by CuddleBear92** [comment]
random example... you are missing the point entirely. there is hundreds of tags that can easily be merged. having tags being imported from sites like chub makes this a larger issue. just cause you don't use it it doesn't mean others don't either.

you can think of any word and tag you want and you have alternatives that users can write. all of it makes sense in the end once you start sharing characters.

**Comment by Woisek** [comment]
I'm not sure if I 'don't get the point'. Your given examples may make sense from the point of view of a hoarder or a unorganized person. And yes, I also use tags, but I use my own system. And if I import a foreign card, then it will be edited for my system because it will probably not match in all terms.
And sharing is also no valid reason, on the contrary. Especially when sharing, the tags should be consistent and the same and not what everyone thinks. And that's exactly why you apparently want this feature, because everyone writes their own terms in and everything then becomes somehow irrelevant and not helpful and you end up (re)changing everything yourself..

But maybe not everyone is a organized as me or others. 🙂

**Comment by ParaplegicRacehorse** [comment]
Actually, the ability to merge tags would be really cool. Even if it only merged tags whose differences were capitalization. 'RPG' and 'Rpg' and 'rpg' are all the same to me. So are 'SILLYTAVERN', 'SillyTavern', 'sillytavern'. 'girl', 'woman' and 'slut' are all clearly different, though.
But, everyone's mileage is different. Don't bother using logic to compare tags and auto-merge. Just give us the ability in the tag-manager to tick boxes next to the to-be-merged tags and then click a Merge button.
Please.
